#!/bin/bash

source_bucket="your-source-bucket"
source_directory="source-folder/"
destination_directory="destination-folder/"

# Loop through files in the source directory
for file in $(aws s3 ls "s3://$source_bucket/$source_directory" | awk '{print $4}'); do
    new_name="${file// /_}"  # Replace spaces with underscores
    aws s3 cp "s3://$source_bucket/$source_directory$file" "s3://$source_bucket/$destination_directory$new_name"
done
